# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhu_cheng_xu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1116, 862)
        Form.setMinimumSize(QtCore.QSize(1116, 862))
        Form.setMaximumSize(QtCore.QSize(1116, 862))
        self.L_x = QtWidgets.QLineEdit(Form)
        self.L_x.setGeometry(QtCore.QRect(230, 480, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.L_x.setFont(font)
        self.L_x.setText("")
        self.L_x.setObjectName("L_x")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 70, 701, 391))
        self.label.setText("")
        self.label.setObjectName("label")
        self.L_y = QtWidgets.QLineEdit(Form)
        self.L_y.setGeometry(QtCore.QRect(480, 480, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.L_y.setFont(font)
        self.L_y.setText("")
        self.L_y.setObjectName("L_y")
        self.L_z = QtWidgets.QLineEdit(Form)
        self.L_z.setGeometry(QtCore.QRect(630, 600, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.L_z.setFont(font)
        self.L_z.setText("")
        self.L_z.setObjectName("L_z")
        self.L_x_min = QtWidgets.QLineEdit(Form)
        self.L_x_min.setGeometry(QtCore.QRect(720, 480, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.L_x_min.setFont(font)
        self.L_x_min.setText("")
        self.L_x_min.setObjectName("L_x_min")
        self.L_y_min = QtWidgets.QLineEdit(Form)
        self.L_y_min.setGeometry(QtCore.QRect(330, 600, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.L_y_min.setFont(font)
        self.L_y_min.setText("")
        self.L_y_min.setObjectName("L_y_min")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(360, 750, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 750, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "三维定位系统"))
        self.pushButton.setText(_translate("Form", "开始"))
        self.pushButton_2.setText(_translate("Form", "截止"))
